---
abstract: 'Remote admin tool for ubic'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: 0.9
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Rubic
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: 4.30
  Ubic: 1.50
resources:
  bugtracker: https://github.com/jhthorsen/rubic/issues
  homepage: https://metacpan.org/module/Rubic
  license: http://dev.perl.org/licenses/
  repository: https://github.com/jhthorsen/rubic
version: 0.0801
